### ISSUE TITLE
Error in line 29 in app.book.BookDao

### ISSUE THREAD

**Issue by JasonSarwar** [tipsy/spark-basic-structure#14]
There is an error in the line:
```java 
return books.stream().filter(b -> b.getIsbn().equals(isbn)).findFirst().orElse(null);
```
There is no getIsbn() method in the Book class. This may be causing other users to have compile errors.

**Comment by tipsy** [comment]
It should be generated by [lombok](https://projectlombok.org/).

**Comment by JasonSarwar** [comment]
Oh I see. Haha my bad!
