### ISSUE TITLE
Thank you for these examples of Spark framework

### ISSUE THREAD

**Issue by JavaProgrammerLB** [tipsy/spark-basic-structure#4]
I like this example very match.I want to know how can i save these books data into a database such as mysql ? I want use spark to do  some database connect, but there is few  things, can you give me some suggestions?

**Comment by tipsy** [comment]
You're welcome! Did you try the database tutorial?

https://sparktutorials.github.io/2015/04/29/spark-and-sql2o.html: 

> In this tutorial you will learn
> - how to understand if an ORM is the right choice for you
> - how Sql2o (a framework to interface with a database) works
> - **how to integrate Sql2o with Spark**

**Comment by JavaProgrammerLB** [comment]
Yes, it's very kind of you, I get the answer.
