### ISSUE TITLE
Q: Your recommendation where to keep configuration for different environments?

### ISSUE THREAD

**Issue by nikos** [tipsy/spark-basic-structure#5]
Thanks for sharing your great sample application and your ideas on best practices using Spark. I am wondering what would be your tipp when it comes to providing configuration to the application (say database connection strings, or template engine behavior)? 

I am looking for something where you can store the configuration file under version control ie. something lightweight like Confucius (https://github.com/IvanTrendafilov/Confucius) in addition to JOpt Simple for passwords to be not visible in git...

**Comment by tipsy** [comment]
You're welcome!
I just use standard `.properties` files, so `localhost.properties`, `staging.properties`, and `production.properties`. For parsing command line arguments I usually use [args4j](http://args4j.kohsuke.org/).

**Comment by nikos** [comment]
Thanks, David.  Even if it seems trivial it might be worth for covering in docs/tutorial/sample to give users a quick idea on how config aspects fit into spark?

**Comment by tipsy** [comment]
That's a good idea, thanks, I won't do a separate tutorial, but I might add it to this one when I have the time!
