### ISSUE TITLE
need some help about form submit

### ISSUE THREAD

**Issue by HavoStrean** [tipsy/spark-basic-structure#6]
Hi:
 Coding with this project, I get some troubles.
How to get data from api and display data without page reload?
Are there some tips to help me?
Thank you!

**Comment by tipsy** [comment]
If you don't want to reload the page you have to use JavaScript to post the form. This is pretty much unrelated to Spark. You could have a look at this: http://www.firstfewlines.com/post/spark-java-ajax-post-example/
