### ISSUE TITLE
How to create a user Session timeout? 

### ISSUE THREAD

**Issue by mjamelle** [tipsy/spark-basic-structure#8]
Thanks for the example, really helpful!
Playing around with the user sessions login an out. I recognized that there is no session timeout. Any idea how to implement it?

**Comment by tipsy** [comment]
Doesn't it time out after 30 minutes? It should be configurable by via jetty: https://github.com/perwendel/spark/blob/master/src/test/java/spark/embeddedserver/EmbeddedServersTest.java

**Comment by mjamelle** [comment]
No, doesn't. At least in my web service which is based on that structure. Anyhow in meantime I found a solution by setting session timer with request.session().maxInactiveInterval .
Thanks for your response!
